import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "y/utils/api";
import { useEffect, useState } from "react";
import Post from "y/components/Post";
import CreateForm from "y/components/CreateForm";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-black py-4 ">
        <div className="mx-auto max-w-5xl space-y-2">
          <CreateForm />
        
        </div>
      </main>
    </>
  );
};

export default Home;
